language: python
python:
    - "3.5"
services: mysql
before_install:
    - sudo apt-get -qq update
    - sudo apt-get install -y python3-mysql.connector
install: "pip install -r requirements.txt"
before_script:
    - mysql -e 'create database scoremodel;'
    - cp travis_config.py config.py
    - mkdir -p /home/travis/build/PACKED-vzw/scoremodel/logs
    - python3 travis.py
script: py.test
