language: python
python:
    - "3.5"
services: mysql
install: "pip install -r requirements.txt"
before_script:
    - mysql -e 'create database scoremodel;'
    - cp travis_config.py config.py
    - mkdir -p scoremodel/logs
    - touch scoremodel/logs/scoremodel.log
    - python3 travis.py
script: py.test
